version: '2'
services:
    investhood-app:
        image: investhood
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://investhood-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=investhood
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    investhood-mongodb:
        extends:
            file: mongodb.yml
            service: investhood-mongodb
